let campaigns = JSON.parse(localStorage.getItem('dnd_campaigns')) || [];
let globalNotices = JSON.parse(localStorage.getItem('dnd_global_notices')) || [];
let currentCampaignId = localStorage.getItem('dnd_current_campaign') || null;
let currentRole = localStorage.getItem('dnd_role') || 'master';
let party = [];
let srdData = { classes: [], races: [], genders: ["Masculino", "Femenino", "No binario"], monsters: [], weapons: [], armor: [], items: [] };
let diceTray = [];
let currentMonster = null;
const calculateMod = (val) => { const mod = Math.floor((val - 10) / 2); return mod >= 0 ? "+" + mod : "" + mod; };
function saveAll() { localStorage.setItem('dnd_campaigns', JSON.stringify(campaigns)); localStorage.setItem('dnd_global_notices', JSON.stringify(globalNotices)); localStorage.setItem('dnd_current_campaign', currentCampaignId || ""); localStorage.setItem('dnd_role', currentRole); }
async function loadSRDData() { try { const response = await fetch('data/srd_data.json'); srdData = await response.json(); populateSelects(); if(currentCampaignId) { selectCampaign(currentCampaignId); } else { renderCampaignList(); } } catch (e) { console.error("SRD Fail"); } }
function renderCampaignList() { const container = document.getElementById('campaign-list'); if (!container) return; if (campaigns.length === 0) { container.innerHTML = '<p style="color:#666; font-style:italic; padding:20px;">Sin campañas.</p>'; return; } container.innerHTML = campaigns.map(c => '<div class="campaign-item"><div class="campaign-info" onclick="selectCampaign(\'' + c.id + '\')"><h3 style=\"font-family:\'Cinzel\';color:var(--gold);margin:0;\">' + c.name + '</h3><p style=\"font-size:0.9rem;color:#888;\">' + (c.party || []).length + ' Héroes</p></div><div class=\"campaign-controls\"><button class=\"btn-mini\" onclick=\"deleteCampaign(\'' + c.id + '\')\"><i class=\"fa-solid fa-trash\"></i></button></div></div>').join(''); }
function selectCampaign(id) { const camp = campaigns.find(c => c.id === id); if (!camp) return; currentCampaignId = id; party = camp.party || []; saveAll(); document.getElementById('lobby-overlay').style.display = 'none'; document.getElementById('campaign-title-display').innerText = camp.name; applyRoleUI(); renderNavigation(); showTab('tab-home'); }
function exitToLobby() { currentCampaignId = null; saveAll(); location.reload(); }
function getAveragePartyLevel() { if(party.length === 0) return 1; const total = party.reduce((sum, c) => sum + (parseInt(c.level) || 1), 0); return Math.floor(total / party.length); }
function generateRandomEncounter(mode) { const apl = getAveragePartyLevel(); const targetCR = (mode === 'hard') ? apl + 1 : apl; const matches = srdData.monsters.filter(m => { const mCR = eval(m.cr); return mCR >= targetCR - 0.5 && mCR <= targetCR + 0.5; }); if(matches.length === 0) return alert("No hay monstruos de nivel " + targetCR + " en el manual."); currentMonster = matches[Math.floor(Math.random() * matches.length)]; renderBattleResult(); }
function renderBattleResult() { const container = document.getElementById('battle-result-area'); const m = currentMonster; container.innerHTML = '<div class=\"monster-result-card\"><h3 style=\"font-family:\'Cinzel\'; color:var(--gold); margin-top:0;\">' + m.name + '</h3><p style=\"margin:5px 0;\">' + m.type + ' | CR: ' + m.cr + '</p><div style=\"display:grid; grid-template-columns: 1fr 1fr; gap:10px; margin-top:10px;\"><div style=\"background:#111; padding:10px; border-radius:4px;\">CA: <b>' + m.ac + '</b></div><div style=\"background:#111; padding:10px; border-radius:4px; color:#ff4444;\">PV: <b>' + m.hp + '</b></div></div><button onclick=\"quickLootFromBattle()\" class=\"btn-primary\" style=\"margin-top:15px; background:var(--gold); color:black; font-size:0.8rem;\">RECLAMAR BOTÍN</button></div>'; }
function quickLootFromBattle() { showTab('tab-loot'); document.getElementById('loot-cr').value = eval(currentMonster.cr); if(eval(currentMonster.cr) >= 5) { document.getElementById('is-lair-loot').checked = true; } generateLoot(); }
function generateLoot() { const cr = eval(document.getElementById('loot-cr').value) || 1; const isLair = document.getElementById('is-lair-loot').checked; const container = document.getElementById('loot-result'); const multiplier = isLair ? 10 : 1; const baseCoins = (Math.floor(Math.random() * 20) + 10) * cr * multiplier; const dist = { cp: Math.floor(baseCoins * 0.90), sp: Math.floor(baseCoins * 0.07), gp: Math.floor(baseCoins * 0.025), ep: Math.floor(baseCoins * 0.002) }; const lootItems = []; const itemChance = isLair ? 0.8 : 0.1; if(Math.random() < itemChance) { const allItems = [...srdData.items, ...srdData.weapons]; lootItems.push(allItems[Math.floor(Math.random() * allItems.length)]); } let itemsHtml = ''; if(lootItems.length > 0) { itemsHtml = '<div style=\"margin-top:15px; border-top:1px solid #222; padding-top:10px;\"><p style=\"font-size:0.8rem; color:var(--gold);\">OBJETOS:</p>' + lootItems.map(i => '<p>• ' + i.name + '</p>').join('') + '</div>'; } container.innerHTML = '<div class=\"card\" style=\"background:#111; border:1px dashed var(--gold); text-align:left;\"><h3 style=\"font-family:\'Cinzel\'; color:var(--gold); margin-top:0;\">' + (isLair ? 'TESORO DE GUARIDA' : 'BOTÍN DE CADÁVER') + '</h3><div style=\"display:grid; grid-template-columns:1fr 1fr; gap:10px; font-size:1.1rem; font-weight:bold;\"><div style=\"color:#cd7f32;\">' + dist.cp + ' cp</div><div style=\"color:#c0c0c0;\">' + dist.sp + ' sp</div><div style=\"color:#ffd700;\">' + dist.gp + ' gp</div><div style=\"color:#50c878;\">' + dist.ep + ' ep</div></div>' + itemsHtml + '<p style=\"font-size:0.7rem; color:#444; margin-top:10px;\">Probabilidad de monedas falsas: 12%</p></div>'; }
function searchMonsters() { const q = document.getElementById('monster-search-input').value.toLowerCase(); const res = document.getElementById('monster-search-results'); if(!q) return res.innerHTML = ''; const matches = srdData.monsters.filter(m => m.name.toLowerCase().includes(q)).slice(0, 5); res.innerHTML = matches.map(m => '<div class=\"char-card\" onclick=\"useMonster(\'' + m.name + '\')\"><h3>' + m.name + '</h3><p>CR: ' + m.cr + '</p></div>').join(''); }
function useMonster(name) { currentMonster = srdData.monsters.find(m => m.name === name); renderBattleResult(); }
function createCharacter() { const name = document.getElementById('char-name').value; if(!name) return alert("¡Nombre!"); const classData = srdData.classes.find(c => c.name === document.getElementById('char-class').value); const newChar = { id: Date.now(), name, level: document.getElementById('char-level').value, race: document.getElementById('char-race').value, charClass: classData.name, stats: { str: parseInt(document.getElementById('char-str').value)||10, dex: 10, con: 10, int: 10, wis: 10, cha: 10 }, hp: classData.hit_die, inventory: [], wallet: {cp:0,sp:0,gp:0,ep:0} }; party.push(newChar); saveAll(); renderParty(); }
function renderParty() { const container = document.getElementById('character-list'); if(!container) return; container.innerHTML = party.map(c => '<div class=\"char-card\" style=\"justify-content:space-between;\"><div><h3>' + c.name + '</h3><p>Nivel ' + c.level + ' | ' + c.charClass + '</p></div><button onclick=\"toggleInventory(' + c.id + ')\" style=\"background:transparent; border:1px solid var(--gold); color:var(--gold); border-radius:50%; width:40px; height:40px;\"><i class=\"fa-solid fa-sack-xmark\"></i></button></div>').join(''); }
function toggleInventory(id) { const d = document.getElementById('inv-' + id); d.style.display = d.style.display === 'block' ? 'none' : 'block'; }
function applyRoleUI() { const isM = currentRole === 'master'; document.getElementById('current-role-text').innerText = isM ? 'MASTER' : 'AVENTURERO'; document.body.className = isM ? 'is-master' : 'is-adventurer'; }
function changeRole() { currentRole = document.getElementById('role-selector').value; saveAll(); applyRoleUI(); renderNavigation(); }
function toggleDiceTray() { const t = document.getElementById('dice-overlay'); t.style.display = t.style.display === 'flex' ? 'none' : 'flex'; }
function addDiceToTray(s) { diceTray.push(s); renderDiceTray(); }
function renderDiceTray() { const l = document.getElementById('dice-selected-list'); l.innerHTML = diceTray.join(' + '); }
function rollAllDice() { let t = 0; diceTray.forEach(s => t += Math.floor(Math.random()*s)+1); document.getElementById('dice-result-area').innerHTML = t; }
function renderNavigation() { const nav = document.getElementById('main-nav'); if(!nav) return; const isM = currentRole === 'master'; nav.innerHTML = '<button onclick=\"showTab(\'tab-home\')\"><i class=\"fa-solid fa-house-chimney\"></i><span>Home</span></button>' + (isM ? '<button onclick=\"showTab(\'tab-combat\')\"><i class=\"fa-solid fa-bolt\"></i><span>Batalla</span></button><button onclick=\"showTab(\'tab-loot\')\"><i class=\"fa-solid fa-gem\"></i><span>Oro</span></button>' : '') + '<button onclick=\"showTab(\'tab-community\')\"><i class=\"fa-solid fa-bullhorn\"></i><span>Tablón</span></button><button onclick=\"showTab(\'tab-party\')\"><i class=\"fa-solid fa-users-rays\"></i><span>Gremio</span></button>'; }
function showTab(t) { document.querySelectorAll('.tab-content').forEach(el => el.style.display = 'none'); document.getElementById(t).style.display = 'block'; if(t === 'tab-party') renderParty(); }
function populateSelects() { document.getElementById('char-class').innerHTML = srdData.classes.map(c => '<option value=\"' + c.name + '\">' + c.name + '</option>').join(''); document.getElementById('char-race').innerHTML = srdData.races.map(r => '<option value=\"' + r.name + '\">' + r.name + '</option>').join(''); }
function deleteCampaign(id) { if(confirm("¿Borrar?")) { campaigns = campaigns.filter(c => c.id !== id); saveAll(); renderCampaignList(); } }
document.addEventListener('DOMContentLoaded', loadSRDData);
window.showTab = showTab; window.toggleDiceTray = toggleDiceTray; window.addDiceToTray = addDiceToTray; window.rollAllDice = rollAllDice; window.createCharacter = createCharacter; window.selectCampaign = selectCampaign; window.exitToLobby = exitToLobby; window.changeRole = changeRole; window.generateLoot = generateLoot; window.generateRandomEncounter = generateRandomEncounter; window.quickLootFromBattle = quickLootFromBattle; window.searchMonsters = searchMonsters; window.useMonster = useMonster; window.toggleInventory = toggleInventory; window.deleteCampaign = deleteCampaign;
